allowBuilds:
  keccak: set this to true or false
  secp256k1: set this to true or false
minimumReleaseAgeExclude:
  - braces@3.0.3
  - ws@7.5.10
  - secp256k1@4.0.4
  - undici@5.28.5
  - cookie@0.7.0
  - base-x@3.0.11
  - brace-expansion@1.1.12
  - brace-expansion@2.0.2
  - pbkdf2@3.1.3
  - sha.js@2.4.12
  - cipher-base@1.0.5
  - tmp@0.2.4
  - undici@5.28.4
  - lodash@4.17.23
  - undici@6.23.0
  - diff@4.0.4
  - diff@5.2.2
  - js-yaml@4.1.1
  - undici@5.29.0
  - bn.js@5.2.3
  - bn.js@4.12.3
  - minimatch@3.1.3
  - minimatch@5.1.7
  - minimatch@5.1.8
  - minimatch@3.1.4
  - serialize-javascript@7.0.3
  - undici@6.24.0
  - '@openzeppelin/contracts-upgradeable@4.9.6'
  - '@openzeppelin/contracts@4.9.6'
  - brace-expansion@1.1.13
  - brace-expansion@2.0.3
  - picomatch@2.3.2
  - serialize-javascript@7.0.5
  - lodash@4.18.0
  - follow-redirects@1.16.0
  - serialize-javascript@6.0.2
  - uuid@14.0.0
  - immutable@4.3.8
overrides:
  undici: ^6.24.0
  '@openzeppelin/contracts-upgradeable@>=4.5.0 <4.9.6': ^4.9.6
  '@openzeppelin/contracts@>=4.5.0 <4.9.6': ^4.9.6
  base-x@<=3.0.10: ^3.0.11
  bn.js@<4.12.3: ^4.12.3
  bn.js@>=5.0.0 <5.2.3: ^5.2.3
  brace-expansion@<1.1.13: ^1.1.13
  brace-expansion@>=1.0.0 <=1.1.11: ^1.1.12
  brace-expansion@>=2.0.0 <2.0.3: ^2.0.3
  brace-expansion@>=2.0.0 <=2.0.1: ^2.0.2
  braces@<3.0.3: ^3.0.3
  cipher-base@<=1.0.4: ^1.0.5
  cookie@<0.7.0: ^0.7.0
  diff@>=4.0.0 <4.0.4: ^4.0.4
  diff@>=5.0.0 <5.2.2: ^5.2.2
  follow-redirects@<=1.15.11: ^1.16.0
  immutable@>=4.0.0-rc.1 <4.3.8: ^4.3.8
  js-yaml@>=4.0.0 <4.1.1: ^4.1.1
  lodash@<=4.17.23: ^4.18.0
  lodash@>=4.0.0 <=4.17.22: ^4.17.23
  lodash@>=4.0.0 <=4.17.23: ^4.18.0
  minimatch@<3.1.3: ^3.1.3
  minimatch@<3.1.4: ^3.1.4
  minimatch@>=5.0.0 <5.1.7: ^5.1.7
  minimatch@>=5.0.0 <5.1.8: ^5.1.8
  pbkdf2@>=1.0.0 <=3.1.2: ^3.1.3
  pbkdf2@>=3.0.10 <=3.1.2: ^3.1.3
  picomatch@<2.3.2: ^2.3.2
  secp256k1@>=4.0.0 <4.0.4: ^4.0.4
  serialize-javascript@<7.0.5: ^7.0.5
  serialize-javascript@<=7.0.2: ^7.0.3
  serialize-javascript@>=6.0.0 <6.0.2: ^6.0.2
  sha.js@<=2.4.11: ^2.4.12
  tmp@<=0.2.3: ^0.2.4
  uuid@<14.0.0: ^14.0.0
  ws@>=7.0.0 <7.5.10: ^7.5.10
