[package]
name = "aptos-escrow"
version = "1.0.0"
authors = []

[addresses]
aptos_escrow_addr="_"

[dev-addresses]
aptos_escrow_addr="0x100"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
