[package]
name = "FungibleAssetVoting"
version = "1.0.0"
authors = []

[addresses]
voting_app_addr = "_"
fa_obj_addr = "_"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "mainnet", subdir = "aptos-move/framework/aptos-framework" }

[dev-dependencies]