export const ABI = {
  address: "0xe7ce55d8dc68c348bb180f44510f73555b53981f1be98406d9f63be2074b4f2d",
  name: "message_board",
  friends: [],
  exposed_functions: [
    {
      name: "get_message_content",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: [
        "0x1::object::Object<0xe7ce55d8dc68c348bb180f44510f73555b53981f1be98406d9f63be2074b4f2d::message_board::Message>",
      ],
      return: [
        "bool",
        "0x1::string::String",
        "u64",
        "address",
        "0x1::object::Object<0x1::object::ObjectCore>",
        "vector<0x1::string::String>",
        "0x1::option::Option<bool>",
        "0x1::option::Option<0x1::string::String>",
        "0x1::option::Option<u64>",
        "0x1::option::Option<address>",
        "0x1::option::Option<0x1::object::Object<0x1::object::ObjectCore>>",
        "0x1::option::Option<vector<0x1::string::String>>",
      ],
    },
    {
      name: "get_message_struct",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: [
        "0x1::object::Object<0xe7ce55d8dc68c348bb180f44510f73555b53981f1be98406d9f63be2074b4f2d::message_board::Message>",
      ],
      return: [
        "0xe7ce55d8dc68c348bb180f44510f73555b53981f1be98406d9f63be2074b4f2d::message_board::Message",
      ],
    },
    {
      name: "get_messages",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ["0x1::option::Option<u64>", "0x1::option::Option<u64>"],
      return: [
        "vector<0x1::object::Object<0xe7ce55d8dc68c348bb180f44510f73555b53981f1be98406d9f63be2074b4f2d::message_board::Message>>",
      ],
    },
    {
      name: "post_message",
      visibility: "public",
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: [
        "&signer",
        "bool",
        "0x1::string::String",
        "u64",
        "address",
        "0x1::object::Object<0x1::object::ObjectCore>",
        "vector<0x1::string::String>",
        "0x1::option::Option<bool>",
        "0x1::option::Option<0x1::string::String>",
        "0x1::option::Option<u64>",
        "0x1::option::Option<address>",
        "0x1::option::Option<0x1::object::Object<0x1::object::ObjectCore>>",
        "0x1::option::Option<vector<0x1::string::String>>",
      ],
      return: [],
    },
  ],
  structs: [
    {
      name: "Message",
      is_native: false,
      abilities: ["copy", "drop", "key"],
      generic_type_params: [],
      fields: [
        { name: "boolean_content", type: "bool" },
        { name: "string_content", type: "0x1::string::String" },
        { name: "number_content", type: "u64" },
        { name: "address_content", type: "address" },
        {
          name: "object_content",
          type: "0x1::object::Object<0x1::object::ObjectCore>",
        },
        { name: "vector_content", type: "vector<0x1::string::String>" },
        { name: "optional_boolean_content", type: "0x1::option::Option<bool>" },
        {
          name: "optional_string_content",
          type: "0x1::option::Option<0x1::string::String>",
        },
        { name: "optional_number_content", type: "0x1::option::Option<u64>" },
        {
          name: "optional_address_content",
          type: "0x1::option::Option<address>",
        },
        {
          name: "optional_object_content",
          type: "0x1::option::Option<0x1::object::Object<0x1::object::ObjectCore>>",
        },
        {
          name: "optional_vector_content",
          type: "0x1::option::Option<vector<0x1::string::String>>",
        },
      ],
    },
    {
      name: "MessageBoard",
      is_native: false,
      abilities: ["key"],
      generic_type_params: [],
      fields: [
        {
          name: "messages",
          type: "vector<0x1::object::Object<0xe7ce55d8dc68c348bb180f44510f73555b53981f1be98406d9f63be2074b4f2d::message_board::Message>>",
        },
      ],
    },
  ],
} as const;
