[package]
name = "FungibleAssetWithPermission"
version = "0.0.0"

[addresses]
permissioned_fa_addr = "_"

[dev-addresses]
permissioned_fa_addr = "0x10"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-framework.git", subdir = "aptos-framework", rev = "mainnet" }
